version: '3.8'

services:
  frontend-app:
    build: . 
    container_name: frontend-cont 
    ports:
      - '3130:3130'
    depends_on:
      - mongodb  
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myDatabase
      - SESSION_SECRET=1234
      - PORT=3130
      - EMAIL_USER=chagantyteja2502@gmail.com
      - EMAIL_PASS=yxoq bjuk rdnt alzp
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=soapmac055@gmail.com
      - GF_SMTP_PASSWORD=qrel zono cfhz caek
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=soapmac055@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Alerts
  mongodb:
    image: mongo:latest 
    ports:
      - '27017:27017'
